### ISSUE TITLE
Make it into a plugin

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#1]
Make it into a plugin so its easier to use

**Comment by patrek** [comment]
Did not create any, but found this: http://patrickwalters.net/making-out-first-plugin/

**Comment by vegarringdal** [comment]
@patrek thx, Ill have a look at that after I have fixed the bugs found

**Comment by vegarringdal** [comment]
Did some tests here:
https://github.com/vegarringdal/test
Loading css as global resources is failing

Added issue here:
https://github.com/aurelia/skeleton-plugin/issues/26

**Comment by vegarringdal** [comment]
work in progress, closing this for now
