### ISSUE TITLE
Missing glyphicons File

### ISSUE THREAD

**Issue by Vaccano** [vegarringdal/aureliaGrid#18]
When I run I get an error trying to get this file:

> GET https://myComputer.myDomain.net/styles/glyphicons-halflings-regular-fromBootstrap.woff2 

I was able to work around this by finding the above file in my bootstrap folder, copying it to my `styles` folder, and then editing `v-grid.css` line 269 to not have a leading `/` before `styles`.

**Comment by vegarringdal** [comment]
Thank you, added something extra to no1, on how to use

> 1: Copy the files under vgrid folder to you src folder, **and move font and spinner image to styles folder**
