### ISSUE TITLE
Error when collection is not defined

### ISSUE THREAD

**Issue by Vaccano** [vegarringdal/aureliaGrid#19]
NOTE: This is a very minor report.  Feel free to ignore it if you prefer.

I am trying to setup the grid in my application.

I wired it up, but I had not run the query that fills the grid at startup.  (So my `collection` value was `undefined`.)

```
 private searchResults: EntityInterfaces.IShipmentSearchPartial[];
```

When that happened I got the following error:

> TypeError: Cannot read property 'slice' of undefined

This was faling in v-grid.js in the `bind` method.

I changed my code to be like this and it got past the error:

```
private searchResults: EntityInterfaces.IShipmentSearchPartial[] = [];
```

**Comment by Vaccano** [comment]
This is listed in the "readme" as a requirement.

My bad.

**Comment by vegarringdal** [comment]
I could maybe throw an error that tells better whats wrong, "missing config collection" etc
Ill have a look at this later, so people done debug in the blind
