### ISSUE TITLE
Feature: Double Click Callback

### ISSUE THREAD

**Issue by Vaccano** [vegarringdal/aureliaGrid#21]
My current scenario that I am trying to enable is a search result grid.  (I need the filtering a sorting abilities of a grid, but none of the editing abilities.)

Basically, want the grid to show a single line selection (`multi-select=false`).  That works great.

Then I want to the user to double click on a search result.  That will result me loading the full record for that item into another control.

**It would be nice to have double click fire a callback with the row that was double clicked.**

Others would probably want the cell that was double clicked too.

**Comment by vegarringdal** [comment]
Yes, I had that before.
But then the grid was very manual, and not it does all the filtering/sorting for you.
But it should be that hardest part for me to add

**Comment by vegarringdal** [comment]
gave this another though, what if I add a event aggregater into the grid, and you can set under options what event should be called when someone double clicks?
This way its not locked to 1 function, but you can use it in other components to to listen for the event

**Comment by vegarringdal** [comment]
In demo "002" I have 

> row-on-dblclick="onDblClick"

added, this is the name of function in my page, this will now get called with the argument "row" and this is the row of the doubleclicked in the collection binded to grid, not the row number i grid if you have sorted/filtered.
Could this be usefull
