### ISSUE TITLE
Don't enter edit mode if the cell is read-only

### ISSUE THREAD

**Issue by Vaccano** [vegarringdal/aureliaGrid#22]
If a cell is read only, then right now, if it is double clicked, it switches to edit mode, and then the text cannot be altered.

It would be nice if a column is read-only that it does not switch to edit mode at all when it is double clicked.

**Comment by vegarringdal** [comment]
Agree, that could maybe be confusing.
I'll have a look at that

**Comment by vegarringdal** [comment]
http://vegarringdal.github.io/vGrid/demo002/
demo v 16 or higher, can u try if this is more what you was thinking?
column "index" is readonly, so cell will not be in edit mode here
