### ISSUE TITLE
Suggestion: Keyboard actions for edit mode.

### ISSUE THREAD

**Issue by Vaccano** [vegarringdal/aureliaGrid#23]
Not sure how feasible this is, but it would be nice if <enter> started edit mode.

Also, if it can be added <escape> is customary to cancel the edits (and revert to previous value).  

Both of these are "nice to have" features.  Just a suggestion.

**Comment by vegarringdal** [comment]
Agree, could be very usefull.
Was thinking about having option/function you could call to get all edited rows incase you needed to send it to server side.
Would almost haveto add function for unlock/lock then.
The pain would be to have controll if I allow them to delete rows/add also.
And keeping control over it all.
But Ill give it more though when Ive solved the tabbing/click callback etc thats simpler to solve

**Comment by Thanood** [comment]
If I'm not completely off-topic:

You could keep a log of edited/deleted rows and columns.
Or may even better: raise some events at such operations and have the log as a plugin.

Then send the log to a server - that is essentially a diff from the last saved state to the current state.
That way it may even evolve into an undo handler.

**Comment by vegarringdal** [comment]
@Thanood 
Atm I use the collection user send me for filtering, add a key to it, that I need to renew on changes(push/slice/pop etc ), so if Im planing to enable undo etc, I would have to duplicate that array and keep that as my original.
Not impossible, but atm I have the possibility to set onFilter, onSort, onGetElement, collectionLength to user with not to much code, and they could just use server side for fetching data, sorting filtering.
I just wanna make sure I dont lock out this with what ever I add, I want to have a full manual mode for virtual scrolling for server side, where you get 40 and 40 as you need it/scrolls

**Comment by Thanood** [comment]
Undo was just an idea.

Main point was the log. :smile: 
Because of your statement:

> you could call to get all edited rows incase you needed to send it to server side

I think a log of actions would help.

**Comment by vegarringdal** [comment]
@Thanood
Open for all suggestions.
Keeping a copy can be usefull, if user had to supply a unique index it would solve a lot.
Atm the grid is adding a __sgkeyXXXX to the collection to keep track of internal to external collection when filtering etc, need to use something that is random so you can have 2 grids to same collection

**Comment by vegarringdal** [comment]
Will have a serous look into this when grid is more ready for remote data and viewslots handle the cell draw.

**Thinking like this:**
Own attribute to tell grid you are using manual "editMode"
3 functions:
-enterEditMode
-cancelEditMode
-saveEditMode

**-enterEditMode**
When this is set it will keep track of : 
-new -> own internal array
-deleted -> own internal array
-modified it will add something like it does on the selection, like a object into the collection, that contains old data, and one to tell if its edited or not.

**-cancelEditMode**
sets back all data etc..

**-saveEditMode**
-return 3 objects arrays: deleted, new, modified

if you guys have any thought then just write them down, so I know more when I get there

**Comment by vegarringdal** [comment]
Having buttons for edit mode, save and cancel should be possible on row level now by using the tempRef on inputs and on save set values to rowRef, on cancel set rowRef to tempRef.

**Comment by vegarringdal** [comment]
moved to aurelia toolkit, all development will continue there
