### ISSUE TITLE
Suggestion: Filter Names

### ISSUE THREAD

**Issue by Vaccano** [vegarringdal/aureliaGrid#24]
This is a very very small suggestion.  It may even be a matter of preference.  So feel free to close this if you don't want to do it.

Currently `*=` is `begin with` and `=*` is `end with`.

To me, these should be `begins with` and `ends with`.

I guess depends on how you are thinking of it:
- To mach, the value must `begin with` the filter parameter
  or
- Match if the value `begins with` the filter parameter.

To me the second seems more natural.  

As I said, this just my preference.  Feel free to discard this.

**Comment by vegarringdal** [comment]
agree, Ill add it to the code Im working now, so it will be added next time I update main branch.
You will also see it in the next demo (002 one)

**Comment by Vaccano** [comment]
However, to be consistent, if you keep `begin with` and `end with` you should consider changing `contains` to `contain`.  

Though I like `contains`, `begins with`, `ends with` and `equals`.

**Comment by Vaccano** [comment]
`equal` also is different.  It should be `equals` to match `contains`, `starts with` and `ends with`.

**Comment by vegarringdal** [comment]
added the "equals" to my code, but "starts with" would that be better than begins with?

**Comment by Vaccano** [comment]
No, that is just me typing faster than I am thinking.

**Comment by vegarringdal** [comment]
ok, hehe
all the sall suggestions are great, becuase its good to know about, since I do a lot of changes its better to know about them when I do the editing, then rewriting a lot of code again
