### ISSUE TITLE
Refactor column definitions

### ISSUE THREAD

**Issue by JeroenVinke** [vegarringdal/aureliaGrid#33]
Instead all [these arrays](https://github.com/vegarringdal/vGrid/blob/dev-rebuild/vGrid/v-grid-col.js#L55-L66) we can have an array with column definitions. That cleans the code up a bit

**Comment by vegarringdal** [comment]
Good suggestion, thx

**Comment by vegarringdal** [comment]
Looked a bit more on this one, I use this data little bit everywhere, old code just keep expanding, was really just 3 array in the start, header, attribute & width.
This will take a while to refactor, and some parts would need rewrite too.

**Comment by vegarringdal** [comment]
fixed
