### ISSUE TITLE
Use fat arrows

### ISSUE THREAD

**Issue by JeroenVinke** [vegarringdal/aureliaGrid#34]
For example [this](https://github.com/vegarringdal/vGrid/blob/dev-rebuild/vGrid/v-grid-row-cells-input.js#L112-L114) can be written more compact:

``` js
this.content.addEventListener("cellFocus", () => this.content.focus());
```

or [this](https://github.com/vegarringdal/vGrid/blob/dev-rebuild/vGrid/v-grid-row-cells-input.js#L98-L108):

``` js
this.content.onkeydown = (e) => {
      if (this.parent.readOnly() === true && e.keyCode !== 9) {
        return false;
      } else {
        if (!this.parent.editMode()) {
          return false;
        } else {
          return true;
        }
      }
};
```

**Comment by vegarringdal** [comment]
thx, some bad habits/parts that never made the clean up

**Comment by vegarringdal** [comment]
fixed
