### ISSUE TITLE
Consolidate events/eventhandlers

### ISSUE THREAD

**Issue by JeroenVinke** [vegarringdal/aureliaGrid#35]
https://github.com/vegarringdal/vGrid/blob/dev-rebuild/vGrid/v-grid-row-col.js#L128-L135

perhaps it is nicer to create a function on the [v-grid](https://github.com/vegarringdal/vGrid/blob/dev-rebuild/vGrid/v-grid.js) that you can call like:

```
  this.vGrid.raiseEvent("vRowOnDblclick", {
          evt: e,
          data: this.vGrid.vGridCollectionFiltered[this.vGrid.vGridCurrentRow],
          attribute: this.attribute(),
          row: this.vGrid.vGridGetRowKey(this.vGrid.vGridCollectionFiltered[this.vGrid.vGridCurrentRow][this.vGrid.vGridRowKey])
 });
```

the `raiseEvent` function can look like so:

```
  raiseEvent(name, data = {}) {
    let event = new CustomEvent(name, {
      detail: data,
      bubbles: true
    });
    this.element.dispatchEvent(event);

    return event;
  }
```

Then users can subscribe to events like so:

```
        <v-grid
          v-row-onclick.delegate="singleClick($event.detail)"
          v-row-ondblclick.delegate="singleDblClick($event.detail)">
        </v-grid>
```

Whenever a user then doubleclicks on a row, the `singleDbClick` function is called and any data is passed as an argument

Then you can probably clean up [this class](https://github.com/vegarringdal/vGrid/blob/dev-rebuild/vGrid/v-grid-atts.js)

**Comment by vegarringdal** [comment]
Nice one
Keep the suggestions coming :smile:

**Comment by vegarringdal** [comment]
fixed
