### ISSUE TITLE
Rename v-grid-row-col.js to v-grid-cell.js

### ISSUE THREAD

**Issue by JeroenVinke** [vegarringdal/aureliaGrid#36]
Not sure, but I think that `v-grid-cell` is a more descriptive name than `v-grid-row-col`

**Comment by vegarringdal** [comment]
yes and now, atm its a col part of a row, that have the cell inside it..
So if we take and add the template part someone could actually have many cells inside 1 column in 1 row.
I leave it open for now, while I think more about it

**Comment by vegarringdal** [comment]
Updated weekend code, I think v-grid-row-col is best, its column withing a row, that have cells inside it/custom html.
