### ISSUE TITLE
Enable linting

### ISSUE THREAD

**Issue by JeroenVinke** [vegarringdal/aureliaGrid#37]
That will probably happen automatically when you switch it to a plugin, but linting can make your code look a bit cleaner (it will tell you to remove [unnecessary semicolons](https://github.com/vegarringdal/vGrid/blob/dev-rebuild/vGrid/v-grid-clientCtx.js#L237)).

**Comment by vegarringdal** [comment]
I had JS hint endabled in webstorm, but must have been disabled when I updated.
Thanks for spotting those
Looks like it kinda failing some places due to es6 code

**Comment by vegarringdal** [comment]
Closing this for now, this is a IDE problem in my end. Will get this fixed before v1.0
