### ISSUE TITLE
customizable header menu

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#38]
This may be an oversight (on my side) since I'm only starting to read the code.

Is the header context menu actually customizable?
There are a lot of built-in functions and string here: https://github.com/vegarringdal/vGrid/blob/dev-rebuild/vGrid/v-grid-attributes-contextmenu.js

What would I do if I wanted to change them (f.i. localize the menu item texts)?

**Comment by vegarringdal** [comment]
Yes, should be able to do something like that.
Its not build for it yet, but will have that in mind when I clean up, to much repeated code there while I was testing/remaking it

**Comment by vegarringdal** [comment]
moved to aurelia toolkit, all development will continue there
