### ISSUE TITLE
customizable loading screen

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#39]
Loading screen HTML is hard coded [here](https://github.com/vegarringdal/vGrid/blob/06e52bdbb42b9c777f00c22bcab04dd569849bcd/vGrid/v-grid-generator.js#L242-L248). Developers should IMO be able to change that by providing an own template.

**Comment by vegarringdal** [comment]
Good suggestion.

**Comment by vegarringdal** [comment]
moved to aurelia toolkit, all development will continue there
