### ISSUE TITLE
use BindingEngine instead of ObserverLocator

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#42]
As of [this SO post](http://stackoverflow.com/questions/28419242/property-change-subscription-with-aurelia/28437456#28437456) by jdanyow, `ObserverLocator` is now considered Aurelia's "bare metal" (internal) API. Instead, `BindingEngine` should be used to get observers (also described in the post mentioned above).

**Comment by vegarringdal** [comment]
I didnt know about that one.
Will have a look into this and switch it out
