### ISSUE TITLE
rename v-grid-element-col-row.js to v-grid-element-row-col.js

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#43]
fits the actual element name :smile:

**Comment by Thanood** [comment]
Same with `v-grid-element-col-header.js` => `v-grid-element-header-col.js` btw..

**Comment by vegarringdal** [comment]
Yes, agree.

**Comment by vegarringdal** [comment]
https://github.com/vegarringdal/vGrid/issues/36
These are almost about the same.
