### ISSUE TITLE
Change how simple columns work on filter/attribute

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#49]
Change how simple columns work on filter/attribute

better to have it like I use the v-filter, v-sort

At the moment you need to set filter="true" filter-operator="_" and value-converter="name"
Better to do this filter="name|_|valueConverter"

Same with sort, instead of true set it to the attribute you want to sort so its more flexible

**Comment by vegarringdal** [comment]
or maybe just do it even more simple:
rowAttribute="xx"
headerFilterAttribute="xx"
headerLabelAttributes ="xx"
Then its a lot more flexible

**Comment by Thanood** [comment]
I like the valueConverter approach. Also in terms of flexibility, because I can bring my own if I want. :smile: .
