### ISSUE TITLE
Dragging doesnt put column name on the top bar

### ISSUE THREAD

**Issue by activebiz** [vegarringdal/aureliaGrid#51]
Some times the dragging column for the grouping dont place the column name on the top bar. 

![image](https://cloud.githubusercontent.com/assets/2632440/20113581/d7877dde-a5e8-11e6-8003-a185db471b9a.png)

**Comment by vegarringdal** [comment]
Fixed on the source, demo not updated
Btw converted the grid to typescript now, but have some more fixing left before Im done, then Ill continue more on features etc, making plugin.
Do you know a lot about typescript?

**Comment by activebiz** [comment]
Great stuff. 

Yup. I am happy to contribute.

**Comment by vegarringdal** [comment]
@activebiz 
Great.

If you know a lot about typescript then it would be great if you want to contribute with improvments on this : https://github.com/vegarringdal/skeleton-plugin-typescript
Will need it when Ive gotten the main source here more fixed
