### ISSUE TITLE
Ability group column by right click and group

### ISSUE THREAD

**Issue by activebiz** [vegarringdal/aureliaGrid#52]
Although drag and drop is a good way to group columns. Also be nice if you can group column by right click menu.

**Comment by vegarringdal** [comment]
Yes, I want to add this, and hide/option to get columns that are hidden to show them again

**Comment by vegarringdal** [comment]
also updated demo... no best icon. please come with better icon suggestions if you want (stick to font awsome for now, thats the fonts I have)
