### ISSUE TITLE
Using "contains" filter throws an error

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#56]
I'm using the rebuilt grid in a view with a simple configuration:

```html
<v-grid v-grid-connector.bind="gridConnector" v-row-height="25" v-header-height="50" v-panel-height="25" v-footer-height="25" style="height:400px">
  <v-grid-col col-width="200" col-pin-left="true" col-sort="commonName" col-filter="commonName|*" col-field="commonName"></v-grid-col>
  <v-grid-col col-width="400" col-header-name="DN" col-sort="distinguishedName" col-filter="distinguishedName" col-field="distinguishedName"></v-grid-col>
</v-grid>
```

When I enter something into the "commonName" filter, I'm getting this error:
`TypeError: this.valueFormater.fromView is not a function`
at `VGridAttributesFilter.getValue`

I think this is because of the `valueConverters` getter returning a function:
```javascript
  get valueConverters(): {fromView: Function; toView: Function} {
    if (this.vGrid) {
      let valueConverter = this.vGrid.viewResources.getValueConverter.bind(this.vGrid.viewResources);  // <-- function returned here
      return valueConverter;
    } else {
      return {fromView: () => {/* nothing */ }, toView: () => {/* nothing */ } };
    }
  }
```

It leads to `this.valueFormater` being a function and not having a `fromView` member. I guess this should be the result of the function instead.

**Comment by vegarringdal** [comment]
fixed in https://github.com/vegarringdal/vGrid/commit/38f32396c75d09a67fbd95fdc4923dc867176e38
Also pushed new build

**Comment by Thanood** [comment]
confirmed :+1:
