### ISSUE TITLE
Aurelia CLI configuration

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#57]
At the moment I have this CLI config:

```json
          {
            "name": "aurelia-v-grid",
            "path":"../node_modules/aurelia-v-grid/dist/amd",
            "main": "index",
            "resources": [
              "**/*.{css,html,js}"
            ]
          }
```

That is including all `.js` files.
We can possibly get rid of it by exporting everything in `index.js`.

But we don't *need* to. :smiley:
Open for discussion.

**Comment by vegarringdal** [comment]
Great if you could give the updated package.json a try, had `vGrid` in path and not `grid` :-)

**Comment by Thanood** [comment]
> Great if you could give the updated package.json a try, had vGrid in path and not grid :-)

As we talked about in Gitter, that doesn't solve it. And, because with ASP.NET you still need to explicitly set the `resources` arrray, I think it never did. It just loads the files from `node_modules`, which are not in the bundle.
With my setup ans the ASP.NET setup, `node_modules` is inaccessibe and this fails.

**Comment by vegarringdal** [comment]
Added to temp gitbook
https://github.com/vegarringdal/vGrid/issues/69
