### ISSUE TITLE
TypeScript transpile errors

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#60]
As requested in Gitter.. :smiley: 

```
src\grid\attributes\v-drag-drop-col.ts(339,9): error TS7005: Variable 'width' implicitly has an 'any' type.
src\grid\attributes\v-drag-drop-col.ts(506,9): error TS7005: Variable 'draggableTarget' implicitly has an 'any' type.

src\grid\attributes\v-drag-drop-col.ts(546,9): error TS7005: Variable 'curColType' implicitly has an 'any' type.
src\grid\attributes\v-drag-drop-col.ts(547,9): error TS7005: Variable 'curColNo' implicitly has an 'any' type.
src\grid\attributes\v-drag-drop-col.ts(548,9): error TS7005: Variable 'curContext' implicitly has an 'any' type.
src\grid\attributes\v-drag-drop-col.ts(549,9): error TS7005: Variable 'curColumnsArray' implicitly has an 'any' type.

src\grid\columnMarkup.ts(96,9): error TS7005: Variable 'markupArray' implicitly has an 'any[]' type.
src\grid\columnMarkup.ts(124,15): error TS7005: Variable 'style' implicitly has an 'any' type.
src\grid\columnMarkup.ts(210,13): error TS7005: Variable 'style' implicitly has an 'any' type.
src\grid\columnMarkupHelper.ts(9,9): error TS7005: Variable 'type' implicitly has an 'any' type.
src\grid\columnMarkupHelper.ts(59,11): error TS7005: Variable 'inputHeader' implicitly has an 'any' type.
src\grid\columnMarkupHelper.ts(60,11): error TS7005: Variable 'labelHeader' implicitly has an 'any' type.
src\grid\columnMarkupHelper.ts(239,9): error TS7005: Variable 'markup' implicitly has an 'any' type.
src\grid\rowClickHandler.ts(199,9): error TS7005: Variable 'isSel' implicitly has an 'any' type.
src\grid\rowScrollEvents.ts(137,11): error TS7005: Variable 'newTop' implicitly has an 'any' type.
src\grid\viewSlots.ts(53,9): error TS7005: Variable 'context' implicitly has an 'any' type.
src\utils\arrayFilter.ts(34,13): error TS7005: Variable 'rowValue' implicitly has an 'any' type.
src\utils\arrayFilter.ts(35,13): error TS7005: Variable 'filterValue' implicitly has an 'any' type.
src\utils\arrayFilter.ts(37,13): error TS7005: Variable 'newFilterOperator' implicitly has an 'any' type.
src\utils\arrayFilter.ts(48,13): error TS7005: Variable 'type' implicitly has an 'any' type.
```

**Comment by vegarringdal** [comment]
So weird I dont get these errors when running gulp watch

**Comment by vegarringdal** [comment]
@Thanood You get these while running gulp watch on a clone of this repo too ?

**Comment by vegarringdal** [comment]
Please send me you tsConfig when you get these errors, so I can test with them

**Comment by Thanood** [comment]
> You get these while running gulp watch on a clone of this repo too ?

I did **only** test this with a clone of this repo.
That's why I also have the same tsconfig as in this repo. 😃 

I agree there must be a difference. But it's not tsconfig (as long as you did not change your local tsconfig).

**Comment by vegarringdal** [comment]
Im installing node/git etc on local pc, if I dont get errors there then I have no clue how to fix this, hopefully is some mess Ive installed on this pc
Weird part is that if I remove type on some of the code I have, I get error, just wont rigger on these

**Comment by vegarringdal** [comment]
@Thanood 
hmm, didnt get errors there either, what os are you on ?

**Comment by vegarringdal** [comment]
Event tried on a unbutu VM I had, no erros

**Comment by vegarringdal** [comment]
Well, followed the errors you posted inn and did a fix for them, hopefully Ill figure out one day why Im not getting these errros, please close this issue if you dont get any more errors now, build updated

**Comment by Thanood** [comment]
I will try this on a VM, too to see if anything is different.

**Comment by vegarringdal** [comment]
Great, only you should not get any errors now, so you might need to go and edit one of them back :-)

**Comment by Thanood** [comment]
Yes, you're right. 😂

**Comment by vegarringdal** [comment]
If you edit this back to nothing, then you should be able to test:
src\grid\attributes\v-drag-drop-col.ts(339,9): error TS7005: Variable 'width' implicitly has an 'any' type.

**Comment by vegarringdal** [comment]
@Thanood Please report back on what you get now that Ive updated the grid typescript

**Comment by vegarringdal** [comment]
@Thanood Have you had a chance to look at this one ?

**Comment by Thanood** [comment]
~~Trying it right now.~~

No errors! 👍

**Comment by vegarringdal** [comment]
very nice :-)
ts upgrade helped then
