### ISSUE TITLE
Refactory to v-sort and v-filter works

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#61]
@Thanood, Would like to get some quick on some changes Ive been considering.

Been thinking about refactor a little how we use v-sort & col-sort, and v-filter & col-filter
Was thinking something like this

**col-filter & v-filter**
```col-filter="field:XXX;operator:XX;converter:XXXX;keydown:true"```
(the v-filter will be the same, but since that is used in custom html you also need to add "rowRef." to field

**col-sort & v-sort**
```col-sort="field:XXX;asc:false;"```
(v-sort same with the "rowRef", the default-asc is for forcing the grid to sort desc on first click)

This will give these attributes more control, and be much easier to expand later.

**Comment by Thanood** [comment]
Good idea, I like it. :smiley: 
While you're at it, would you consider naming these attributes the same? So the usage is more consistent?
I don't know if it's possible since these are two different attributes/files.

**Comment by vegarringdal** [comment]
1 part is attribute, "col" part is bindables on a custom element `v-grid-col` and used with the v-column binding. So cant have them named the same "col" part is only used with simple html part.
The "col" part is also just so I know how to create the custom html you can define your self if you want.

**Comment by vegarringdal** [comment]
@Thanood this is added now, just so you know update will break you grid if you dont update adding field etc

**Comment by vegarringdal** [comment]
replaced by temp gitbook: https://github.com/vegarringdal/vGrid/issues/69
