### ISSUE TITLE
icons need more work

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#64]
Icons need more work

Maybe use "user ref" and have 1 svg users need to load, that way replacing icons will be easier

Anyways, design of my icons will need more work too, first time Ive ever made svg icons.
So some look very bad atm

**Comment by vegarringdal** [comment]
@Thanood 

this is how the icons look atm, will use https://jakearchibald.github.io/svgomg/ to get size of path data down, and also make them little bit smaler

![image](https://cloud.githubusercontent.com/assets/2901416/20500194/cf109ef0-b034-11e6-844a-c4e8b10f7362.png)

![image](https://cloud.githubusercontent.com/assets/2901416/20500238/ee90cab6-b034-11e6-8a5e-b133a977d0d8.png)


![image](https://cloud.githubusercontent.com/assets/2901416/20500215/e0d6eec8-b034-11e6-8c0e-57eddad4b3c4.png)

![image](https://cloud.githubusercontent.com/assets/2901416/20500247/f774fa9e-b034-11e6-841a-23113076858d.png)

**Comment by vegarringdal** [comment]
Been thinking about skipping this icons craziness on the menu, just have the sort icon, and + and minus for grouping, and X (but nicer for removing grouping

What to you think @Thanood ?

**Comment by Thanood** [comment]
I think there should also be more margin between icons and text. :smiley:

I agree that maybe the operators don't need an icon. Maybe it looks less "bloated" but it may also look good when you make them a bit smaller, as you already said. I'd try both and see how it looks.
