### ISSUE TITLE
inconsistent class naming

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#67]
I have a "simple" column and a "custom html" column. In both, there is a header `<p>`.

The "simple" `<p>` has a class `avg-label-top` while the "custom html" column has `vgrid-label-top`.

**Comment by vegarringdal** [comment]
hmm, looks like I forgot to tell you that the custom html in the old doecs, then ```vgrid-``` in classnames have been renamed to ```avg-```
Thanks for catching that one

**Comment by vegarringdal** [comment]
I did that to get more consistent naming on the classes

**Comment by vegarringdal** [comment]
....wrong post

**Comment by vegarringdal** [comment]
Added to temp gitbook
replaced by temp gitbook: https://github.com/vegarringdal/vGrid/issues/69
