### ISSUE TITLE
Missing word wrap on header

### ISSUE THREAD

**Issue by JOKaija** [vegarringdal/aureliaGrid#76]
Eh... This vGrid "won't work" with headers as v-grid. Seems, It won't split long header names to multiple lines. Now I have ugly header with broken text strings...

Soooo, where is my word wrap? :-)

And how to set "initial" filter method. With v-grid it was easy "data|*"

**Comment by JOKaija** [comment]
Fixed by editing CSS, but there will be a problem, when updating vGrid.

Have to fix css every time...

**Comment by vegarringdal** [comment]
Ill have a look at it later today, guessing it should be easy to add as a option/default

**Comment by vegarringdal** [comment]
new build pushed
It now wraps the text in the header
Still needs to be room for it though...

![image](https://cloud.githubusercontent.com/assets/2901416/21936622/21c54622-d9b2-11e6-8f34-1cf219165f45.png)

**Comment by JOKaija** [comment]
Great!  \o/
