### ISSUE TITLE
Not on issue, requesting simple example...

### ISSUE THREAD

**Issue by JOKaija** [vegarringdal/aureliaGrid#78]
Ok, I have a simple select (for filtering purposes) html. So, I'd like to add this to
column. How to do it?

        <select value.bind="TargetSituation">
            <option value="Kaikki">Kaikki</option>
            <option value="Kesken">Kesken</option>
            <option value="Selvityksessä">Selvityksessä</option>
            <option value="Valmis">Valmis</option>
        </select>

**Comment by vegarringdal** [comment]
not at the computer atm
havent tried to do this but grid allows you to have custom html in columns too
see under custom html in the docs
you will need to do css you self if you are doing the on a column (row or header)

**Comment by JOKaija** [comment]
> see under custom html in the docs

Too narrow documentation for me. I'm stupid. Didn't you know that?

I did try to add html part inside v-grid.context tag without success.
So. I can wait, when you are at your computer and create some great example magics again as you used to ;-)

**Comment by JOKaija** [comment]
Ideal way would be something like this. And with LEFT mouse button on filter area:

```
<v-grid-html-component id="firsthtml">
......anykind html stuff here, what is sized for column header cell size....
</v-grid-html-component>
```

And initializing this at code:

`{colField:"Id", colField:"Id | numberFormatter", colHeaderHtml:"firsthtml"...........`

or something like that....

Then we could use datepicker component for selecting dates too easilly...

**Comment by JOKaija** [comment]
Or for html style select-dropdown (with LEFT click on filter area)

```
options = ["Not ready", "Unfinished", "Ready", "Not needed"];

{colField:"Id", colField:"Id | numberFormatter", colDropDownFilter:"options"...........
```

**Comment by vegarringdal** [comment]
This is the docs for the custom html https://vegarringdal.gitbooks.io/dev-rebuild/content/chap04/ 
You if you done want to set the header part in custom html you just use row part, and add where every you else would use in ```<v-grid-col>```

```
<v-grid-col col-width="30">
  <v-row-template>
         <-------- put your html inside here------------>
  </v-row-template>
</v-grid-col>
```
Only difference is you have set values etc to ```rowRef.attributeName``` or ```tempRef.attributeName``` to bind to values in that row
You can write html like you else would in aurelia here, so you can bind values to model.

**Comment by JOKaija** [comment]
I must miss something now. First of all, if I put that (your code strip) on html, then my all columns have it?
Anyway, this doesn't add anything to my screen. Tested inside "v-grid lotofdefinitions  /v-grid"tag too. 

I should somehow separate this only for needed columns. Ok, I know, I can use if.bind="checkByJsCode(tempRef,"TargetAssemblerName")" to get info about column "name" for visibility, so no problem

**Comment by JOKaija** [comment]
This doesn't show fixed column either...

`    
#v-grid 
                    id="tablepart"
                    style="height:500px; max-width:1860px; font-size:12px"
                    v-row-height="25"
                    v-header-height="75"
                    avg-row-checkbox-50
                    v-panel-height="0"
                    v-footer-height="0"
                    v-grid-connector.bind="gridConnector"
                    v-columns.bind=columnSetup
                    v-language.bind=Lang_Fi
                    v-translate.bind="myObject"
                    v-row-on-draw.call="onRowDraw($event)"
                    v-row-onclick.delegate="singleClick($event.detail)"#

                    #v-grid-col col-width="100"#
                        #v-header-template#
                            #select value.bind="test"#
                                #option value="Kesken"#Kesken#/option#
                                #option value="Ei tarvita"#Ei tarvita#/option#
                                #option value="Valmis"#Valmis#/option#
                            #/select#
                        #/v-header-template#
                    #/v-grid-col#
#/v-grid#
Damn. Had to fix by hand whole code strip. This editor goes grazy with "<" and ">" marks...

**Comment by JOKaija** [comment]
Oh. I maid now why. Since I set up my column definitions on JS side, there maid be overwritten there?

So, how to add whole html code part on js-side to column definitions? That is new to me!

**Comment by vegarringdal** [comment]
the code I posted is one column, you use tje <v-grid-col> tag for all the column in the grid you have allready made, but to put custom html inside 1 you need to put html like the doc says inside that element.
Ill post more code in 20 min when kids have gone to bed :-)

**Comment by vegarringdal** [comment]
Maybe Im just explaining myself badly :-)
I know I have update the docs better
Here is a gist of the old grid, but the basics are the same for both when it comes to custom html
Look at the html part of the grid code on the columns.
https://gist.run/?id=6ad85edc11f552f2afde0bf19bf14333

PS you dont have to do this on all columns, you can do it on just 1 if you one need custom html in 1 of them

**Comment by JOKaija** [comment]
Prev version code didn't help either. I remember, it worked on old version when I fixed those code lines... But with this vGrid. Nothing. I raise my hands up and start to scream :-)

Last situation:
![whatandwhere](https://cloud.githubusercontent.com/assets/18458962/21958230/2ad679ce-dab2-11e6-8f13-48d4d55bf5cc.jpg)

**Comment by vegarringdal** [comment]
hmm, looking at the picture I have miss understood you, my bad
You are using the v-columns from what I can see, cant mix that with the html
For the v-column. binding options you need to use the ```colRowTemplate``` and ```colHeaderTemplate``` to put custom html inside


Here you see all the attributes I have in my interface, they are pretty much the same as the html part
```
export interface ColConfig {
  [key: string]: any;
  colWidth?: number;
  colRowTemplate?: string;
  colHeaderTemplate?: string;
  colField: string;
  colPinLeft?: boolean;
  colPinRight?: boolean;
  colHeaderName?: string;
  colAddLabelAttributes?: string;
  colAddFilterAttributes?: string;
  colAddRowAttributes?: string;
  colFilterMenu?: string;
  colLabelMenu?: string;
  colRowMenu?: string;
  colHidden?: boolean;
  colDragDrop?: string;
  colResizeable?: string;
  colSort?: string;
  colFilter?: string;
  colFilterTop?: boolean;
  colCss?: string;
  colType?: string;
}
```

**Comment by vegarringdal** [comment]
hint: for translation i the new one look here:
https://vegarringdal.gitbooks.io/dev-rebuild/content/chap02/v-language.html

**Comment by JOKaija** [comment]
Hmm, I add colHeaderTemplate to my js columnsetup like:

```
   //column setup  
    columnSetup = [
{colHeaderTemplate:"targetcond"},
{colField:"Id", colField:"Id | numberFormatter", colHeaderTemplate:"testcol"; colSort:"field:Id;asc:true", colHeaderName:"Id", colType:"number", colWidth:100, colFilter: "field:Id" , colFilterMenu:"filter:Id",colAddRowAttributes:"readonly"},
etc....


```
Now, where I put my "targetcond"?
Creating it in html page ie, 

`*span id="targetcond* --- html stuff ----*span*`

or what? I'm so confusing. Spent too many hours only with this and my brain are spaghetti...

**And for clarify. I'm trying to replace filter input box on column with html select code template. OR add html select code template to that same menu to that same column, up, middle or bottom.**


btw. This is the main reason, why I always need good example programs instead of documentations.
Most of documentations contains odd "foo, fii fuu föö fää asdfasdf" words. Just words for idiotic linux computer nerds. Those are just mumbojumbo for me. A good, clear example tells everything :-)
Yep. I'm too old (1966), self learned coder. But I think I know what I'm doing :-) Almost hundred usefull applications since 1984- and now I keep my brain fresh with these kind of things:

http://www.thecolonizers.com
http://www.jarikaija.fi

```

**Comment by vegarringdal** [comment]
```{colField:"TargetCondition_s", colHeaderTemplate:"inside here you put all you markup",```

>Yep. I'm too old (1966), self learned coder.

Me to 1980, didnt try js before 2011 :-)

**Comment by vegarringdal** [comment]
Ill try and make something myself this way, incase I have some bugs or something Ive overlooked

**Comment by vegarringdal** [comment]
> A good, clear example tells everything :-)
I agree, plan is to create gist.run samples later to show different ways doing stuff, they will also be very helpful when people needs to explain a issue to me..
I try and add to the docs as I have time, but most of my time have gone into fixing bugs between my work ( not programming at all) and kids and other things I need to get done :-)
Also trying to add a lot of comments to my datasource and gridConnector class so it will be easier for other to come with fixes, or make own that can be used with the grid
This is the datasource:
https://github.com/vegarringdal/vGrid/blob/dev-rebuild/src/dataSource.ts


**But back to your problem:**

Make a very short and simple code sample here.
only 1 column, result looks bad, but Im not using any styling... so its very easy to se whats going on



>html file

```
<v-grid 
        style="height:400px"
        v-multi-select="true" 
        v-grid-connector.bind="gridConnector" 
        v-row-height="25" 
        v-header-height="50" 
        v-panel-height="25"
        v-footer-height="25"
        v-columns.bind="myColumns">

      </v-grid>
```

> js file

```
let nameRowMarkup = `
      <input value.bind="rowRef.name">
    `;

    let nameHeaderMarkup = `
      <p> My Name </p>
    `;

    this.myColumns = [
      {colField: "name", colHeaderTemplate: nameHeaderMarkup, colRowTemplate: nameRowMarkup}
    ]
```

Produces:

![image](https://cloud.githubusercontent.com/assets/2901416/21958923/02956e3c-dab9-11e6-9c57-436d0a381892.png)

**Comment by JOKaija** [comment]
Now we are talking!!!!! This works... Couple css files for dropdown and between menus and that all.
I can, at last, release this new app version after weekend. So our staff can use it on monday morning.
This table was the best increment of my app. Previous haven't glued menu row, screen height size fixed table neither. I made a little fix to your table, and now it's height will fitt with chrome dev screen too automatically...
![nowwearetalking](https://cloud.githubusercontent.com/assets/18458962/21958970/82c15e3c-dac2-11e6-9fce-c689a7741072.jpg)


There maid be possible binds to use now... such header name from tempRef? Yes, was. You just updated msg over me :-)

**Comment by vegarringdal** [comment]
> There maid be possible binds to use now... such header name from tempRef?

You should be able to bind to variables in you model, I havent tried that in header

If I try in my row and use this it works fine, since I add the binding index to rows parentBindingContext, I might need to improve that part for the header

```
//same as sample before just turned input to button
let nameRowMarkup = `
      <input type="button" click.delegate="buttonClick($this)" value.bind="rowRef.name">
    `;

// class function
buttonClick (event) {
    console.log(event);
  }

```

**Comment by vegarringdal** [comment]
Just tested with this for the headerMarkup

```
let nameHeaderMarkup = `
      <input type="button" click.delegate="buttonClick($this)" value="header button">
    `;
```

its connected to model too, so you should be able to use the samples in aurelia docs for select box

**Comment by vegarringdal** [comment]
Tested with select aurelia way binding to model
Notice: ```$au``` and ```.replace(/\$(au{)/g, '${')```
Have these so js done replace the text with string interpolation right away... easier to use multiline text when writing html in js 


```
this.products = [
      { id: 0, name: 'Motherboard' },
      { id: 1, name: 'CPU' },
      { id: 2, name: 'Memory' },
    ];

    this.selectedProductId = null;

    let nameRowMarkup = `
      <input type="button" click.delegate="buttonClick($this)" value.bind="rowRef.name">
    `;

    let nameHeaderMarkup = `
      <select value.bind="selectedProductId">
      <option model.bind="null">Choose...</option>
      <option repeat.for="product of products"
              model.bind="product.id">
        $au{product.id} - $au{product.name}
      </option>
    </select>
    `.replace(/\$(au{)/g, '${');

    this.myColumns = [
      {colField: "name", colHeaderTemplate: nameHeaderMarkup, colRowTemplate: nameRowMarkup}
    ]

```

**Comment by JOKaija** [comment]
Nice!

Just tested. DatePicker works just fine too :-)

Btw, may I use several filter options for one column. Same way, what you made for -between- filter.
I have couple dropdown options, which should show multiple variations...

For triggering I use aurelias observer:
```
import {MultiObserver} from 'multi-observer';



@inject(HttpClient, Router, DialogService, ApplicationState, MultiObserver)
export class assembleredit 
{
    
    constructor(http, router,  dialogService, applicationState, multiObserver) 
    {
        this.multiObserver = multiObserver;
clipclip
propertyChanged()
{
// here we go....
}
clipclip
attach(
        this.subscription = this.multiObserver.observe(
          this.datatoobserve, () => this.propertyChanged());
```
This will raise event and with this my filter routine fires instantly after dropdown/date/ "single/between"
searches...

**Comment by vegarringdal** [comment]
> Btw, may I use several filter options for one column. Same way, what you made for -between- filter.
I have couple dropdown options, which should show multiple variations...

With the custom html you can do a lot, that why I have it because its impossible for me to create everything built into the grid, just needed to have the basics there
So you really create the header and 2 inputs or selected and query with between with code if you want.
If you run into issues we just haveto selve them as they come, since Im sure someone witll try and do something I havent though about
Im sure there is 100 things that I haveto do some minor or major changes as you and @Thanood uses it.
But this is why I dont want to many users on it, because I might need to do breaking changes, so be careful when getting variables from the classes by code, usually function I dont change

For the selected you can also use bindable


```javascript
import { bindable } from 'aurelia-framework';

export class App {
@bindable selectedProductId = null;


selectedProductIdChanged(newValue, oldvalue){
    console.log(newValue)
  }

constructor(){

   this.products = [
      { id: 0, name: 'Motherboard' },
      { id: 1, name: 'CPU' },
      { id: 2, name: 'Memory' },
    ];

    let nameRowMarkup = `
      <input type="button" click.delegate="buttonClick($this)" value.bind="rowRef.name">
    `;

    let nameHeaderMarkup = `
      <select value.bind="selectedProductId">
      <option model.bind="null">Choose...</option>
      <option repeat.for="product of products"
              model.bind="product.id">
        $au{product.id} - $au{product.name}
      </option>
    </select>
    `.replace(/\$(au{)/g, '${');

    this.myColumns = [
      {colField: "name", colHeaderTemplate: nameHeaderMarkup, colRowTemplate: nameRowMarkup}
    ]
}

}
```

**Comment by vegarringdal** [comment]
btw if you make some good css classes that work with my optional existin ones then I wil consider adding them to my css so its easier to add normal select

Here you see the name of the classes used when not using custom html
PS! notice I use "avg-" not "vgrid" like picture shows

https://vegarringdal.gitbooks.io/dev-rebuild/content/chap05/

Source
https://github.com/vegarringdal/vGrid/blob/dev-rebuild/src/grid/styles/cellsAndLabels.css

**Comment by vegarringdal** [comment]
And feel free to use the gitter channel too, I always answer when I get time, just a bit busy some days.
(great you make issues here, easier for me to keep track, great you close them when its solved too)
If I dont answer the other aurelia-toolkit team members might answer before me
The other team members are the ones that created the kendoui-bridge and materlizecss-bridge for aurelia, monterey app, so they know what they are doing :-)
