### ISSUE TITLE
How can i have a row read only

### ISSUE THREAD

**Issue by mabouchalkha** [vegarringdal/aureliaGrid#83]
Hi,

nice grid,
is there any way to have the grid on read-only mode. don't want to edit the value in the grid

thank you

**Comment by vegarringdal** [comment]
>Hi,
nice grid,
is there any way to have the grid on read-only mode. don't want to edit the value in the grid
thank you

Thx, its not perfect, but Im trying :-)

Dont have one simple for setting entire row or grid
But under column setup you can use the ```col-add-row-attributes``` to add custom/extra normal ones to the inputs/checkboxes, like ```readonly``` or ```disabled```
```
<v-grid>
  x-attributes..
x-attributes..

  <v-grid-col 
     col-field="someattribute"
     col-add-row-attributes"readonly">
  </v-grid-col>

</v-grid>
```

https://vegarringdal.gitbooks.io/dev-rebuild/content/chap03/col-add-row-attributes.html

**Comment by vegarringdal** [comment]
Guessing you got it working just fine
