### ISSUE TITLE
Rebuild the dragdrop

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#85]
Rebuild the dragdrop/improve the dragdrop

Maybe just indicate where drop will be?

**Comment by vegarringdal** [comment]
@Thanood 
Experimenting with auto hidden column, and have option in menu to drag it in

![cool](https://cloud.githubusercontent.com/assets/2901416/24716161/53c43f2c-1a2e-11e7-8cb0-794b607b354c.gif)

**Comment by vegarringdal** [comment]
Looks like the basic hide/column chooser is working
Just need to clean up menu part before I push new version and test column html in menu and update docs


![longest ever](https://cloud.githubusercontent.com/assets/2901416/24766935/804acf78-1afd-11e7-8b21-dd8e552a43ba.gif)

**Comment by Thanood** [comment]
I love that.. 😃 

Just an idea:
Could you restrict the drag animation to the x-axis and move it along the header line?

**Comment by vegarringdal** [comment]
>Could you restrict the drag animation to the x-axis and move it along the header line?

@Thanood 
But then you cant drag it from then menu, or from header to group panel.
Or did I miss something ?
Well anyways have a lot of clean up to do, and see if I can make it a little more stable/ optimise how I do some of the stuff, little bit messy atm.
Was thinking about just indicate where the drop will be like Ive seen in other grids, but looks like this is working

**Comment by Thanood** [comment]
> But then you cant drag it from then menu, or from header to group panel.

I mean only when adding a new column from the menu.
