### ISSUE TITLE
selecting "enable resizable headers" when horizontally scrolled messes up header to column alignment.

### ISSUE THREAD

**Issue by Vaccano** [vegarringdal/aureliaGrid#9]
Repro:
1. Load the demo and press "get all"
2. Enable resizable headers
3. Resize a few headers so that the horizontal scroll bar appears.
4. Scroll right (so that you cannot see the index column)
5. Press "enable resizable columns" (or disable resizeable columns)
Result: The headers all resize to fit the width on screen, not logical width that the scroll bar goes to.

**Comment by vegarringdal** [comment]
thx, I should test if resizable headers is active first.
reason for the bug is that I rebuild the header when activating it
should be a pretty easy fix

**Comment by vegarringdal** [comment]
Need to check if content.scrollLeft is changed for all options that changed header options, 
- if scrollleft > 0 then also rebuild rows.
- If the active filter user is setting is active then do not do anything
