### ISSUE TITLE
Control markup contains a square bracket [

### ISSUE THREAD

**Issue by mikhailshilkov** [vegarringdal/aureliaGrid#90]
Control markup contains a square bracket [ :

![image](https://cloud.githubusercontent.com/assets/1454008/26554340/dc1e17b8-448f-11e7-8dc2-77d0dca60581.png)

I tried to find from where it comes, but failed so far...

**Comment by vegarringdal** [comment]
hi, what sample/code are you using? 
Looks like the demo.
Need some more information to help :-)

**Comment by mikhailshilkov** [comment]
That's your demo, I just changed the theme class to non-exiting one.
We use a custom theme with transparent background, and then "[" is visible.  But it's always in HTML.

**Comment by vegarringdal** [comment]
really weird.
never seen that one before.
anyway you can show me the steps to reproduce it?
would like to fix this if its a bug, did you rebuild the demo with newer grid then the live demo, or did you just make css changes to the live demo?
what browser do you use/any extensions that could be interfering?

**Comment by mikhailshilkov** [comment]
Just F12 in Chrome and then you can find it in front of `v-grid` closing tag.
To see it, change the CSS class of `v-grid` from `avg-default` to `avg-default2`.

**Comment by vegarringdal** [comment]
thx, Ill have a look after work tomorrow, need sleep now.

**Comment by vegarringdal** [comment]
Its a bug, can be shown by removing color of panel
Try and figure out later tonight what is causing it

Update:
https://github.com/vegarringdal/vGrid/blob/dev-rebuild/src/grid/loadingScreen.ts#L57
This is prb the cause of bug

**Comment by vegarringdal** [comment]
@mikhailshilkov Ive fixed the bug and updated the live demo

**Comment by mikhailshilkov** [comment]
Thanks for being so quick!

**Comment by vegarringdal** [comment]
@mikhailshilkov 
Np :-) Had time to do it yesterday between other things, also started making the scroll events passive.
Started on a step by step guide in the docs, but havent gotten very far since its summer and need to do a lot of other things too.

Do you use the grid in any project atm, or just testing?

**Comment by mikhailshilkov** [comment]
Yes, we use it in our B2B product, currently in beta, should go live next month. We mostly use it for virtual scroll and row groupings so far. Great work!

**Comment by vegarringdal** [comment]
Great, good luck on your product :-)

Also started on this:
https://github.com/vegarringdal/trackSource

Its alternative datasource for it, but havent gotten very far since I ended up trying to get Aurelia to work with fusebox bundler and like I said last post, its summer so have a lot of other things to  do :-)
https://github.com/fuse-box/fuse-box-aurelia-seed


Please post some pictures if you can, would like to see how you style it.

**Comment by mikhailshilkov** [comment]
Here is a sample picture:
![image](https://cloud.githubusercontent.com/assets/1454008/26678677/e95c7cc8-46d1-11e7-8d44-40e7e471d5d1.png)

It's also updated real-time from web socket pushes, the grid works quite nicely (although we had to hack into data source a bit).

**Comment by vegarringdal** [comment]
@mikhailshilkov 

> It's also updated real-time from web socket pushes, the grid works quite nicely 

Looks very nice

> (although we had to hack into data source a bit).

Yes, one of the reasons why I have the gridconnector and datasource  when I started making a new grid  is to make modifications to datasource simpler and without the need for me to update the grid.

If you have seen some bugs then please make a PR or tell me about it, most of my work have gone into the grid, and havent tested everything in every way possible :-)

**Comment by vegarringdal** [comment]
@mikhailshilkov 

Anything you guys have been missing in features, found docs hard to understand etc ?

**Comment by vegarringdal** [comment]
@mikhailshilkov
Just saw the youtube video, your app looks very good.
