### ISSUE TITLE
remove gulp

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#95]
https://github.com/vegarringdal/vGrid/tree/remove-gulp

Todo

- [x] remove gulp and folders
- [x] get watch running
- [x] add build
- [x] get build commonjs
- [x] get build amd (do we even need this, does every loader support commonjs)
- [x] get build system  (do we even need this, does every loader support commonjs)
- [x] clean up
- [x] make dummy npm release (aurelia-v-grid@1.1.0-next.2)
- [x] try plugin in demo by installing dummy release

**Comment by shahabganji** [comment]
@vegarringdal 
What do you mean by 
> make dummy npm release 

Is it within the plugin to sync it with its sample project?

**Comment by vegarringdal** [comment]
`npm install aurelia-v-grid` installs the official

but Ive tagged the package.json with `-next.2`  and done `npm publish --tag next` (dunno if if I need the `next`,  but it den generates package `aurelia-v-grid@1.1.0-next.2`
very useful for beta/feature tests

**Comment by shahabganji** [comment]
aha, I thought a dummy package while in developing stage just to handle the deps between plugin and sample
